// lib/models/boarder_model.dart
import 'package:hive/hive.dart';

part 'boarder_model.g.dart';  // Generated by build_runner

@HiveType(typeId: 0)
class BoarderModel extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String name;

  @HiveField(2)  // Add this for room
  final String room;

  @HiveField(3)  // Add this for rent
  final String rent;  // Using String for now; change to double if you want numeric handling

  BoarderModel({
    required this.id,
    required this.name,
    required this.room,  // Add this parameter
    required this.rent,  // Add this parameter
  });

  // Optional: Factory for JSON (if using APIs)
  factory BoarderModel.fromJson(Map<String, dynamic> json) {
    return BoarderModel(
      id: json['id'] as String,
      name: json['name'] as String,
      room: json['room'] as String,
      rent: json['rent'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'room': room,
      'rent': rent,
    };
  }
}